### ISSUE TITLE
UnrealEnginePython_20170203_4_14_python36_win64.zip fails to load.

### ISSUE THREAD

**Issue by matthewkapfhammer** [20tab/UnrealEnginePython#119]
Windows 10
UE-4.14.3
UnrealEnginePython_20170203_4_14_python36_win64

Starting from a new, empty project in UE 4.14.3, I launched and enabled the plugin.

An error pop-up is triggered during application start up:
```
Plugin `UnrealEnginePython` failed to load because module `UnrealEnginePython` could not be loaded. There may be an operating system error or the module may not be properly set up.
```

**Comment by rdeioris** [comment]
Hi, are you sure you have python3.6 in system PATH ? The non-embedded distribution expects to find python36.dll. Does it work with the embedded one ?

**Comment by matthewkapfhammer** [comment]
The short answer is: Yes, that was the issue.

**Comment by MatzeOGH** [comment]
@rdeioris I have the same problem. Win10, UE4.15, Python36
I have no problem launching python from the power shell but the plugin does not work.
I set the PATH variable to C:\Program Files\Python36

Steps:
1. download python 3.6 from https://www.python.org/downloads/
2. install for all users & set the path to C:\Program Files\Python36
3. install UE4 plugin
4. start project
5. fail: "plugin `UnrealEnginePython` failed to load because module `UnrealEnginePython` could not be loaded. There may be an operating system error or the module may not be properly set up."

I have the same problem on two different machines

**Comment by rdeioris** [comment]
@MatzeOGH  have you tried the embedded distribution ?

Can you try copying python36.dll into the plugin binary directory ?

**Comment by MatzeOGH** [comment]
It was my own fault. 
I mistakenly installed the Win32 version
