### ISSUE TITLE
[Question] Threading/ ue4 waits for script to finish

### ISSUE THREAD

**Issue by JernejHabjan** [20tab/UnrealEnginePython#326]
Hi,
Im running Monte-Carlo tree search algorithm in python and im calling python script every 1 seconds from blueprint.
In script it runs 5000 simulations for tree search, which causes game to lag for like 0.2 seconds.
How should i run (if its possible) python script, for game not to lag.
I dont know much about threading, but can it be run in seperate thread, and after finish, message back that it processed result.
Thanks

**Comment by rdeioris** [comment]
Hi, can you 'split' the computation part in multiple steps ? (like processing a subset of the 5000 items at each iteration). In this way you can use coroutines (via asyncio https://github.com/20tab/UnrealEnginePython/blob/master/tutorials/AsyncIOAndUnrealEngine.md) or the upcoming generators support

**Comment by JernejHabjan** [comment]
Hi,
I would just like to run python script not on Game thread, but on my own. Just like ue4 multithreading works.
The only thing i want to achieve is on every 1 sec i would run python script async, when it's done it would message string result back. But this computation would take like .5 seconds.

I've tried to inherit pyComponent, where i could implement ue4 multithreading in c++, but no luck.
The algorithm cant really be splitted, because at every iteration(simulation) it updates previous results.
With asyncIO, does sleep mean that task is sleeping on other thread or is game thread waiting for it to finish?

**Comment by rdeioris** [comment]
If you cannot suspend the algorithm, you can only use threads. So get a threaded build of the plugin, create a python Thread for running the algorithm and use a queue (https://docs.python.org/3/library/queue.html) to pass back informations to ue4. Note: use get_nowait() in the ue4 part, otherwise the engine will block again

**Comment by JernejHabjan** [comment]
Hey sorry if im bothering you, but i don't know really how to work with plugin, where to get methods that are avaliable by ue (import unreal_engine as ue), so i could call get_nowait()

I've enabled multithreading in UnrealEnginePythonPrivatePCH.h (uncommented #define UEPY_THREADING 1),
made threads in py file, which i'm calling from pyComponent, which looks like this:

![image](https://user-images.githubusercontent.com/21958321/36640656-9dea5abe-1a23-11e8-84ff-1412d57add75.png)

But Game still locks, because ue.get_nowait() is not working (don't know how to use it). And you said that after completion, i should speak back to ue with queue - may I ask how would that look like.
i would like to set component (thats runnig script) variable like self.uobject.myvar= 1

**Comment by rdeioris** [comment]
get_nowait() is a python queue method: https://docs.python.org/3/library/queue.html

check the link for more infos. Basically once the thread is started you need a ticker function (or an actor/component if you want to get the result from the game play) that periodically checks the python queue

**Comment by JernejHabjan** [comment]
Hey

Im really breaking my head with this :)
Ive downloaded threaded build, created thread for function that i want to run, which is only printing string in python console for now, but game still laggs everytime function is called. I dont know what i am doing wrong, because you said that i will be using queue for storing results, but it doesnt help me get code async.
Im calling CallPythonComponentMethod, which inits threads and starts function, but then game waits for "CallPythonComponentMethod" to finish?
I cant figure this out with python.
Is there any way, that i call python script / function (and then recieve data) from c++ multithreaded class?

**Comment by rdeioris** [comment]
I will try to be most clear as possible, otherwise i suggest you to buy support from my company :)

* You Actor/Component generates a python thread, and the Actor/Component MUST NOT join it. To be mear clear the thread must be daemonzed: https://docs.python.org/3/library/threading.html#thread-objects (daemon = True)
* Now the thread is running and will write (when ready) the result of its computation in a python queue
* Another Actor/Component in the world will start "polling" the queue using get_nowait() at every tick. This Tick function will exit suddenly if the thread has not finished its job
* As soon as get_nowait() returns an item, it means the thread has finished its job

**Comment by JernejHabjan** [comment]
Ok thanks, this makes things clearer :) You can close the issue and thanks again
