### ISSUE TITLE
Saving an asset

### ISSUE THREAD

**Issue by LarsGroh** [20tab/UnrealEnginePython#36]
Hi,
I changed the material on a StaticMesh using "my_asset.Materials = [...]". I discovered that the material changes are lost on restart of the editor if I don't open the static mesh and save it manually.

How can I save it by script? I looked into "save_package". but didn't really get ho to work it in order to save in place:
https://docs.unrealengine.com/latest/INT/API/Runtime/CoreUObject/UObject/UPackage/SavePackage/index.html

I "simply" want to trigger the same behaviour as if I was pressing the save button in the editor.

**Comment by rdeioris** [comment]
save_package() is the way to go, as it takes care of saving the asset and updating the content browser (as well as invalidating objects). It is like the c++ version, but on steroids :)

Your problem is that you need to find the asset path to pass to save_package().

Fortunately you only need to call get_outer() on the object to access is package:

```py
package_name = my_asset.get_outer().get_name()
my_asset.save_package(package_name)
```

**Comment by LarsGroh** [comment]
Thanks! That worked perfectly!

**Comment by jiamingfeng** [comment]
I tried the following code to save the Blueprint asset I created but it is still mark as dirty even though it said finished SavePackage:

```
ue.compile_blueprint(layoutBP)
layoutName = layoutBP.get_outer().get_name()
layoutBP.save_package(layoutName )
```

The asset still has a * in the thumbnail.

**Comment by rdeioris** [comment]
should be fixed now. The dirty mark is applied only before save

**Comment by rdeioris** [comment]
Can we close it ?
