### ISSUE TITLE
How to Parent BlueprintActor StaticMeshComponent and SceneComponent

### ISSUE THREAD

**Issue by t-yknk** [20tab/UnrealEnginePython#584]
Hello,I want to create hierarchy in BlueprintActor
I am poor at English, so I will put an image

・SceneComponent to parent SceneComponent
・StaticMeshComponent to parent SceneComponent

```
import unreal_engine as ue

from unreal_engine.classes import Actor,SceneComponent
from unreal_engine.classes import StaticMeshComponent,StaticMesh
from unreal_engine.classes import Blueprint

bp = ue.load_object(Blueprint,'/Game/Developers/TEST')

ue.add_component_to_blueprint(bp,SceneComponent,"Door")
ue.add_component_to_blueprint(bp,SceneComponent,"RH")

for item in ue.get_selected_assets():
	name=item.get_name()
	geo=ue.load_object(StaticMesh,"/Game/Developers/" + str(name))

	new_component = ue.add_component_to_blueprint(bp,StaticMeshComponent,str(name))`
	new_component.StaticMesh = geo

ue.compile_blueprint(bp)
```

![default](https://user-images.githubusercontent.com/35734885/47791440-13484300-dd5d-11e8-8b9f-dd20d70741c8.jpg)

**Comment by iMitrandir** [comment]
doesn't know if it will help, but did you try .functions() method on your actor or bp? there are a bunch of methods that are related to components etc

**Comment by t-yknk** [comment]
thank you for answering
But it does not go well.

I decided to lower the difficulty level.
I forgot, but I am a very beginner.

I examined the API as advised. I can not understand the C language
However, I found a description close to what I wanted to do

parent.AddNode (RH)

Although this does not work
But my wish is transmitted. So I wrote.
```
import unreal_engine as ue

from unreal_engine.classes import Actor,SceneComponent
from unreal_engine.classes import StaticMeshComponent,StaticMesh
from unreal_engine.classes import Blueprint

bp = ue.load_object(Blueprint,'/Game/Developers/TEST')

ue.add_component_to_blueprint(bp,SceneComponent,"Door")
ue.add_component_to_blueprint(bp,SceneComponent,"RH")

Door = bp.SimpleConstructionScript.DefaultSceneRootNode.ChildNodes[0]
RH = bp.SimpleConstructionScript.DefaultSceneRootNode.ChildNodes[1]

parent = bp.SimpleConstructionScript.DefaultSceneRootNode.ChildNodes[0].ComponentTemplate

print(parent)

parent.AddNode(RH)
```
![3](https://user-images.githubusercontent.com/35734885/47855008-af8a4c80-de26-11e8-83ac-247a5c659e47.jpg)
![2](https://user-images.githubusercontent.com/35734885/47854641-9b921b00-de25-11e8-94eb-6652c53c57c9.jpg)

**Comment by AndyZhou1123** [comment]
hi try this i just figured out it because there is no transform in skeleton on sequencer if i use bp to add so i add a static mesh as a parent just use for transform


bp = ue.create_blueprint(Actor,'/Game/test')
stCmp = ue.add_component_to_blueprint(bp,StaticMeshComponent,'Test_ST')
skCmp = ue.add_component_to_blueprint(bp,SkeletalMeshComponent,'Test_SK')
SKnode =  bp.SimpleConstructionScript.AllNodes[-1]
Parent = bp.SimpleConstructionScript.RootNodes[0].ChildNodes[-2]
childNode = []
childNode.append(SKnode)
Parent.ChildNodes = childNode
stList = bp.SimpleConstructionScript.RootNodes[0].ChildNodes
stList.pop()
bp.SimpleConstructionScript.RootNodes[0].ChildNodes = stList
ue.compile_blueprint(bp)
