### ISSUE TITLE
 how move the specified folder instead of a file ?

### ISSUE THREAD

**Issue by lsr1994** [20tab/UnrealEnginePython#645]
Hey, guys. I want to use python to move the specified folder instead of a file, such as '/Game/Materials/' folder to '/Game/Test/Materials/' what should I do? Ask for help! Thank you.

**Comment by dfb** [comment]
I'm not one of the project devs, so don't take this as any sort of official answer: I looked and didn't see any builtin way to do this currently - maybe one of the devs know of something and can point it out.

That said, you can probably achieve the same result on your own by combining a couple of different pieces that do exist:
- ```unreal_engine.rename_asset(oldPath, newPath)``` to move an individual asset between folders - note that this will create new subfolders for you as needed
- ```unreal_engine.get_assets(path, True)``` - recursively list assets in a folder and all subfolders

**Comment by lsr1994** [comment]
@dfb   Thank you, my dear friend.

**Comment by kakyoism** [comment]
@dfb  Does this also fix the redirectors, as the context menu Fix up Redirectors in Folder do ?

**Comment by dfb** [comment]
That's a great question, but unfortunately I don't know the answer - I'm not very familiar with how the engine handles redirectors internally.

The good news, though, is that you should be able to perform a simple experiment to discover the answer because you can look to see what redirectors exist (see https://docs.unrealengine.com/en-us/Engine/Basics/Redirectors) - so you could manually move a folder in the editor and verify that you see a redirector show up, and then you could do a similar rename but via Python and see if a redirector is created.
