### ISSUE TITLE
Is it possible to generate and use pyc files

### ISSUE THREAD

**Issue by amadlover** [20tab/UnrealEnginePython#716]

**Comment by jonlm** [comment]
For anything I run in Content/Scripts I'm seeing pyc files get properly created in __pycache__ subdirectories. Are you not seeing that? What python version are you using? (Note: I'm a new user of UnrealEnginePython, not one of its developers)

**Comment by amadlover** [comment]
Hey, I am interested  in using python with Unreal Engine. I am curious to know if compiled python files are created, so they can be distributed.

**Comment by dfb** [comment]
As @jonlm noted, you should be seeing pyc files in `__pycache__` directories under Content/Scripts - are you not seeing those? pyc's are typically generated as a byproduct of loading the module.

If you want, you can also generate them manually and include them in your packaged build so that you don't have to ship the .py files:

```py
import py_compile
py_compile.compile('foo.py', 'foo.pyc', optimize=2)
```
We do the above and ship just the pyc files in our packaged builds. Note that if you're doing this for security reasons, it adds a smidgen of security, but pyc's are pretty easily decompiled, so it's more obscuring than securing your code. It'll probably keep honest people honest at least! :)

**Comment by amadlover** [comment]
Hello, thank you for the information. However, i have not had the opportunity to check this out. Closing this for now.
